// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package factory

import (
	"github.com/TemaKut/tt-perx/internal/app/config"
	"github.com/TemaKut/tt-perx/internal/app/handlers/http/math"
)

// Injectors from wire.go:

func InitApp(cfg *config.Config) (*App, func(), error) {
	logger, err := ProvideLogger(cfg)
	if err != nil {
		return nil, nil, err
	}
	queue, cleanup := ProvideQueue()
	service, cleanup2 := ProvideMathService(cfg, queue, logger)
	handler := math.NewHandler(service)
	httpServer, cleanup3, err := ProvideHttpServer(cfg, handler, logger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	httpProvider := ProvideHttpProvider(httpServer)
	app, cleanup4 := ProvideApp(logger, httpProvider)
	return app, func() {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
