// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package factory

import (
	"github.com/TemaKut/tt-perx/internal/app/config"
	"github.com/TemaKut/tt-perx/internal/app/handlers/http/math"
	"github.com/TemaKut/tt-perx/internal/service/math"
	"github.com/TemaKut/tt-perx/internal/storage/math"
)

// Injectors from wire.go:

func InitApp() (*App, func(), error) {
	configConfig := config.NewConfig()
	logger, err := ProvideLogger(configConfig)
	if err != nil {
		return nil, nil, err
	}
	queue := mathstore.NewQueue()
	service := mathsvc.NewService(queue)
	handler := math.NewHandler(service)
	httpServer, cleanup, err := ProvideHttpServer(configConfig, handler, logger)
	if err != nil {
		return nil, nil, err
	}
	httpProvider := ProvideHttpProvider(httpServer)
	app, cleanup2 := ProvideApp(logger, httpProvider)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
